const productos = [ 
    { id: 0,
      nombre: "Camiseta Barcelona ", 
      precio: 2500,
      descripcion: "Camiseta",
      categoria: "Camisetas",
      url: "/imagenes/Prenda1.jpg",
      stock: 10},
    { id: 1,
      nombre: "Abrigo Sair",
      precio: 8.990,
      descripcion: "ABRIGO CAPUCHA",
      categoria: "Abrigos",
      url: "/imagenes/Prenda2.jpg",
      stock: 5},
    { id: 2,
      nombre: "Sacón Manchester ", 
      precio: 7000,
      descripcion: "ABRIGO DE PAÑO",
      categoria: "Abrigos",
      url: "/imagenes/Prenda3.jpg",
      stock: 6},
    { id: 3,
      nombre: "Jersey Corspe",
      precio: 5.590,
      descripcion: "JERSEY CROPPED",
      categoria: "Otros",
      url: "/imagenes/prenda4.jpg",
      stock: 10},    
    { id: 4,
      nombre: "Pantalon Melissa",
      precio: 5500,
      descripcion: "Pantalon de vestir",
      categoria: "Otros",
      url: "/imagenes/Prenda5.webp",
      stock: 4},    
    { id: 5,
      nombre: "Cazadora Borussia ",
      precio: 9.190,
      descripcion: "CAZADORA ACOLCHADA EFECTO PIEL",
      categoria: "Abrigos",
      url: "/imagenes/prenda6.webp",
      stock: 10},    
    { id: 6,
      nombre: "Camiseta Banfilth",
      precio: 2.990,
      descripcion: "CAMISETA RIB MANGA ABULLONADA",
      categoria: "Camisetas",
      url: "/imagenes/prenda7.webp",
      stock: 5},    
    { id: 7,
      nombre: "Sudadera Madrid",
      precio: 3500,
      descripcion: "SUDADERA BÁSICA",
      categoria: "Abrigos",
      url: "/imagenes/prenda8.webp",
      stock: 10}] ;

export default productos ;